settings:
  name: "StorageGRID"
  search: "storagegrid-enable,storagegrid-117"
  downlevel: true
  internal:
    pdf_enabled: false
    termcheck_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: true
    hide_language_selector: false
  versions:
    - version-number: "11.7"
      url: /storagegrid-117
    - version-number: "11.9"
      url: /storagegrid
    - version-number: "11.8"
      url: /storagegrid-118         
    - version-number: "11.6"
      url: /storagegrid-116    
    - version-number: "11.5" 
      url: /storagegrid-115  
sidebar:
  entries:
    - title: StorageGRID 11.7 docs
      url: /index.html
    - title: Release notes
      url: "/release-notes/index.html"
    - title: Get started
      entries:
      - section: primer
      - section: network
      - title: Quick start for StorageGRID
        url: /primer/quick-start.html      
    - title: Install and upgrade
      entries:
      - section: installconfig
      - section: rhel
      - section: ubuntu
      - section: vmware
      - section: upgrade
    - title: Configure and manage
      entries:
      - section: admin
      - section: ilm
      - section: harden
      - section: fabricpool
    - title: Use StorageGRID
      entries:
      - section: tenant
      - section: s3
      - section: swift
    - title: Monitor and troubleshoot
      entries:
      - section: monitor
      - section: troubleshoot
      - section: audit
    - title: Maintain
      entries:
      - section: expand
      - section: maintain
      - section: commonhardware
      - section: sg6100
      - section: sg6000
      - section: sg5700
      - section: sg5600
      - section: sg100-1000
    - title: Enable StorageGRID
      url: /storagegrid-enable.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: StorageGRID documentation
  repo: storagegrid-family