settings:
  name: "Product Name"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: StorageGRID 11.7 Docs
      url: /index.html
    - section: release-notes
    - title: Get started (NO CHANGE)
      entries:
      - section: primer
      - section: network
    - title: Install (NEW)
      entries:
      - section: installconfig
      - title: Software nodes
        entries:
        - section: rhel
        - section: ubuntu
        - section: vmware
    - title: System administration (NO CHANGE)
      entries:  
      - section: admin
      - section: ilm
      - section: harden
      - section: fabricpool
    - title: Use StorageGRID (NO CHANGE)
      entries: 
      - section: tenant
      - section: s3
      - section: swift
    - title: Monitor and troubleshoot (NEW)
      entries:  
      - section: monitor  
      - section: troubleshoot
      - section: audit
    - title: Upgrade and maintain (NEW)
      entries:
      - section: upgrade
      - section: expand
      - section: maintain
      - title: Maintain appliance hardware
        entries:
        - section: commonhardware
        - section: sg100-1000n
        - section: sg6000n
        - section: sg5700n
        - section: sg5600n
    - title: Earlier versions
      url: /earlier-versions.html
    - title: Legal notices
      url: /legal-notices.html 
